import type { Metadata } from "next";
import { Playfair_Display } from 'next/font/google';
import "./globals.css";
import Header from "./navbar";
import Footer from "./footer";


const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], 
  display: 'swap', 
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playfair.className} >
          <div className="">
            <Header />
          </div>
          <div className="px-20 pt-40">
            {children}
          </div>
          <div>
            <Footer />
          </div>
      </body>
    </html>
  );
}
